FROM alpine
#ARG DOMAIN
RUN apk add --no-cache openssl
WORKDIR /certs
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /certs/localhost.key \
    -out /certs/localhost.crt \
    -subj "/C=CO/ST=Bogota/L=Bogota/O=ArquisoftUNAL/OU=Habitus/CN=localhost"

VOLUME /certs