FROM alpine
ENV DOMAIN localhost
RUN apk add --no-cache openssl
WORKDIR /certs
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /certs/${DOMAIN}.key \
    -out /certs/${DOMAIN}.crt \
    -subj "/C=CO/ST=Bogota/L=Bogota/O=ArquisoftUNAL/OU=Habitus/CN=${DOMAIN}"

VOLUME /certs